name: Lint

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: '1.8.3'

      - name: Install dependencies (dev only)
        run: poetry install --with dev --no-root

      - name: Ruff check
        run: poetry run ruff check .

